# The Site Configuration

# Import the theme

remote_theme: cotes2020/jekyll-theme-chirpy

# Plugins required for GitHub Pages

plugins:

* jekyll-remote-theme

lang: en
timezone: Asia/Kolkata

title: Vishwa
tagline: "Learn, Break, Understand, Repeat!"

description: >-
A space where I share CTF writeups, red team insights, and my journey
through the world of hacking and cybersecurity.

url: "https://vkumxr.github.io"
baseurl: "/portfolio"

github:
username: vkumxr

twitter:
username: vkumxrr

social:
name: Vishwa Kumar Venkateswaran
email: [vishwakumarv05@gmail.com](mailto:vishwakumarv05@gmail.com)
links:
- https://x.com/vkumxrr
- https://github.com/vkumxr
- https://www.linkedin.com/in/vishwakumarv/

avatar: https://ih1.redbubble.net/image.5524525391.6495/st,medium,507x507-pad,600x600,f8f8f8.jpg

toc: true
paginate: 10

kramdown:
syntax_highlighter: rouge
syntax_highlighter_opts:
css_class: highlight

collections:
tabs:
output: true
sort_by: order

defaults:

* scope:
  path: ""
  type: posts
  values:
  layout: post
  toc: true
  permalink: /posts/:title/

sass:
style: compressed

exclude:

* "*.gem"
* "*.gemspec"
* docs
* tools
* README.md
* LICENSE

